version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: /tmp
    steps:
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir /tmp/artifacts
            pytest --junitxml=/tmp/artifacts/junit.xml

      - store_test_results:
          path: /tmp/artifacts

      - store_artifacts:
          path: /tmp/artifacts
