version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: /tmp
    steps:
      - run:
          name: Save test results
          command: |
            mkdir -p ~ /tmp/artifact-1;
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~ /tmp/artifact-1 \;
          when: always
      - store_test_results:
          path: ~ /tmp/artifact-1
      - store_artifacts:
          path:  /tmp/artifact-1
