version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: /tmp
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir
            skjdnfksdjfnksdfj" > /tmp/artifacts/artifact-2;
            echo "my artifact files in a dir and some extra data" > /tmp/artifacts/artifact-3;
           
            
      
      - store_artifacts:
          path: /tmp/artifact-1
      
      - store_artifacts:
          path: /tmp/artifacts/artifact-2
      - store_artifacts:
          path: /tmp/artifacts/artifact-3
      
