version: 2.1
orbs:
    hello: circleci/hello-build@0.0.5
        workflows:
            "Hello Workflow":
        jobs:
          - hello/hello-build
        working_directory: /tmp
    steps:
        - run:
            command: |
                echo Running test
                mkdir -p /tmp/test-results
                make test

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/artifacts
