version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: /tmp
    steps:
      - run:
          name: Save test results
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2
            mkdir -p /tmp/artifacts
            bundle exec cucumber --format pretty --format json --out /tmp/artifacts/tests.cucumber
          when: always
      - store_test_results:
          path: /tmp/artifact-1
      - store_test_results:
          path: /tmp/artifacts/tests.cucumber
      - store_test_results:
          path: /tmp/artifacts
