version: 2
jobs:
    build_and_save:
        docker:
        - image: circleci/golang:latest
        steps:
            - checkout
            upload-artifact:
            docker:
                - image: circleci/golang:latest
            - store_artifacts:
                path: /bin/final_build
workflows:
    version: 2
    main:
        jobs:
            - build_and_save
