version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
#     working_directory: /tmp
    steps:
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir test-results
            pytest --junitxml=test-results/junit.xml

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
