version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: /tmp
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
             echo Running test
                mkdir -p /tmp/test-results
                make test

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/artifacts
