version: 2
jobs:
    build_and_save:
        docker:
        - image: circleci/hello-world:latest
        - auth:
            username: shan3222
            password: shan@1234  # context / project UI env-var reference
        steps:
            - checkout
            - run: make build
            - store_artifacts:
                path: /bin/final_build
workflows:
    version: 2
    main:
        jobs:
            - build_and_save
