version: 2

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: hello-world:latest
        auth:
          username: shan3222
          password: shan@1234  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: hello-world:latest
        auth:
          username: shan3222
          password: shan@1234  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"
    
      - store_test_results:
          path: C:\Users\RetailAdmin\Music\circleci
          destination: circle

# Orchestrate our job run sequence
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
